Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2018-11, with the labels that each got.

#43 Support for custom domains.
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Country.swift
  WordPressKit/DomainContactInformation.swift
  WordPressKit/DomainsServiceRemote.swift
  WordPressKit/JSONDecoderExtension.swift
  WordPressKit/PlanServiceRemote.swift
  WordPressKit/PlanServiceRemote_ApiVersion1_3.swift
  WordPressKit/RemotePlan_ApiVersion1_3.swift
  WordPressKit/State.swift
  WordPressKit/TransactionsServiceRemote.swift
  WordPressKitTests/DomainsServiceRemoteRESTTests.swift
  WordPressKitTests/Mock Data/domain-contact-information-response-success.json
  WordPressKitTests/Mock Data/site-plans-v3-bad-json-failure.json
  WordPressKitTests/Mock Data/site-plans-v3-empty-failure.json
  WordPressKitTests/Mock Data/site-plans-v3-success.json
  WordPressKitTests/Mock Data/supported-countries-success.json
  WordPressKitTests/Mock Data/supported-states-empty.json
  WordPressKitTests/Mock Data/supported-states-success.json
  WordPressKitTests/Mock Data/validate-domain-contact-information-response-fail.json
  WordPressKitTests/Mock Data/validate-domain-contact-information-response-success.json
  WordPressKitTests/PlanServiceRemoteTests.swift
  WordPressKitTests/TransactionsServiceRemoteTests.swift
Labels: [Status] In Progress

#53 Blog: get all authors API
  Podfile.lock
  WordPressKit.podspec
  WordPressKit/BlogServiceRemote.h
  WordPressKit/BlogServiceRemoteREST.m
  WordPressKit/BlogServiceRemoteXMLRPC.m
  WordPressKitTests/BlogServiceRemoteRESTTests.m
Labels: History / Revisions, enhancement

#57 Fix/xmlrpc sticky post
  Podfile.lock
  WordPressKit.podspec
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/PostServiceRemoteXMLRPC.m
  WordPressKit/RemotePost.h
  WordPressKitTests/PostServiceRemoteRESTTests.m
  WordPressKitTests/PostServiceRemoteXMLRPCTests.swift
Labels: bug
