Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2019-03, with the labels that each got.

#116 Fix of numerical tag sync on WP.com
  WordPressKit.podspec
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/PostServiceRemoteRESTTests.m
Labels: bug

#123 Update to version 3.1.1
  WordPressKit.podspec
Labels: enhancement

#124 [Jetpack Remote Install] New Blog service API
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BlogServiceRemoteREST+Jetpack.swift
  WordPressKitTests/BlogServiceRemoteRESTTests+Jetpack.swift
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-activation-failure.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-activation-install.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-activation-response.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-forbidden.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-install-failure.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-install-response.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-invalid-credentials.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-login-failure.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-site-is-jetpack.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-error-unknown.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-failure.json
  WordPressKitTests/Mock Data/blog-service-jetpack-remote-success.json
Labels: Jetpack

#126 Fix category update
  WordPressKit.podspec
  WordPressKit/PostServiceRemoteREST.m
Labels: bug

#129 Remove objc annotation from Plans service method with incompatible Obj-C types
  WordPressKit.podspec
  WordPressKit/PlanServiceRemote_ApiVersion1_3.swift
Labels: bug
