Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2019-07, with the labels that each got.

#171 [Jetpack] Update Jetpack Remote Install Error
  WordPressKit.podspec
  WordPressKit/JetpackServiceRemote.swift
  WordPressKitTests/JetpackServiceRemoteTests.swift
Labels: Jetpack

#173 Update podfile version
  WordPressKit.podspec
Labels: bug

#172 [Update Username] Map new property in account settings GET and new method
  WordPressKit.podspec
  WordPressKit/AccountSettings.swift
  WordPressKit/AccountSettingsRemote.swift
  WordPressKitTests/AccountSettingsRemoteTests.swift
Labels: enhancement

#166 Implement POST editor settings
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/EditorServiceRemote.swift
  WordPressKit/EditorSettings.swift
  WordPressKitTests/EditorServiceRemoteTests.swift
Labels: enhancement
