Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2019-02, with the labels that each got.

#87 Add support for locale key injection
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/ActivityServiceRemote.swift
  WordPressKit/ActivityServiceRemote_ApiVersion1_0.swift
  WordPressKit/WordPressComRestApi.swift
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/WordPressComRestApiTests+Locale.swift
Labels: enhancement

#99 Fix a bug causing strange build issues
  Podfile
  Podfile.lock
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/StatsLastPostInsight.swift
  WordPressKit/StatsServiceRemoteV2.swift
Labels: bug, enhancement

#105 Apply some Swift 4 cleanup
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AccountSettingsRemote.swift
  WordPressKit/GravatarServiceRemote.swift
  WordPressKit/HTTPAuthenticationAlertController.swift
  WordPressKit/NotificationSyncServiceRemote.swift
  WordPressKit/PluginServiceRemote.swift
  WordPressKit/RemoteBlogSettings.swift
  WordPressKit/RemoteNotificationSettings.swift
  WordPressKit/SharingServiceRemote.swift
  WordPressKit/SiteManagementServiceRemote.swift
  WordPressKit/WordPressComOAuthClient.swift
  WordPressKit/WordPressOrgXMLRPCApi.swift
  WordPressKit/WordPressOrgXMLRPCValidator.swift
  WordPressKit/WordPressRSDParser.swift
  WordPressKitTests/JSONLoader.swift
  WordPressKitTests/WordPressComOAuthTests.swift
  WordPressKitTests/WordPressComServiceRemoteRestTests.swift
  WordPressKitTests/WordPressOrgXMLRPCApiTests.swift
Labels: enhancement

#113 Ensure that nil parameters don't defeat locale handling
  WordPressKit.podspec
  WordPressKit/WordPressComRestApi.swift
  WordPressKitTests/WordPressComRestApiTests+Locale.swift
Labels: bug

#103 Modified existing services to leverage locale handling
  WordPressKit.podspec
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/ActivityServiceRemote.swift
  WordPressKit/PlanServiceRemote.swift
  WordPressKit/PlanServiceRemote_ApiVersion1_3.swift
  WordPressKit/ReaderSiteSearchServiceRemote.swift
  WordPressKit/TimeZoneServiceRemote.swift
  WordPressKit/WordPressComServiceRemote.h
  WordPressKit/WordPressComServiceRemote.m
  WordPressKitTests/WordPressComServiceRemoteRestTests.swift
Labels: enhancement

#114 Removed obsolete BB postbuild script
  buddybuild_postbuild.sh
Labels: enhancement
