Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2020-03, with the labels that each got.

#220 Fixes the error handling in our email checking service.
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/RemoteTestCase.swift
Labels: bug

#221 Merge 4.5.7.1 into develop.
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/RemoteTestCase.swift
Labels: bug

#223 Merge release 4.5.9 into develop
  WordPressKit.podspec
Labels: releases

#222 Release/4.5.9
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/RemoteBlogOptionsHelper.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/RemoteTestCase.swift
Labels: releases

#225 Update `wpxmlrpc` pod
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
Labels: enhancement

#227 Atomic Authentication Service.
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AtomicAuthenticationServiceRemote.swift
  WordPressKitTests/AtomicAuthenticationServiceRemoteTests.swift
  WordPressKitTests/Mock Data/atomic-get-auth-cookie-success.json
Labels: enhancement

#226 Improve loading of large media libraries
  Gemfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit/MediaServiceRemote.h
  WordPressKit/MediaServiceRemoteREST.m
  WordPressKit/MediaServiceRemoteXMLRPC.m
  WordPressKitTests/MediaServiceRemoteRESTTests.swift
Labels: enhancement

#229 Update dependency NSObject-SafeExpectations to v 0.0.4
  Podfile
  Podfile.lock
  WordPressKit.podspec
Labels: enhancement

#230 Use Doubles for price values.
  Gemfile.lock
  WordPressKit.podspec
  WordPressKit/RemotePlan_ApiVersion1_3.swift
  WordPressKitTests/Mock Data/site-plans-v3-success.json
Labels: bug

#231 Pin the ruby version for this project
  .ruby-version
Labels: enhancement

#232 Migrate to Swift 5
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKit.xcscheme
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKitTests.xcscheme
  WordPressKit/CocoaLumberjack.swift
  WordPressKit/PluginDirectoryEntry.swift
  WordPressKit/WordPressComOAuthClient.swift
  WordPressKit/WordPressOrgXMLRPCValidator.swift
  WordPressKitTests/BlogServiceRemoteRESTTests.m
  WordPressKitTests/ReaderSiteServiceRemoteTests.swift
  WordPressKitTests/RemoteTestCase.swift
  WordPressKitTests/WordPressComOAuthTests.swift
  WordPressKitTests/WordPressComRestApiTests.swift
  WordPressKitTests/WordPressComServiceRemoteRestTests.swift
  WordPressKitTests/WordPressOrgXMLRPCApiTests.swift
Labels: enhancement

#235 Fixes a SignUp regression.
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
Labels: bug

#236 Merge Release/4.6.0 back into develop
  Podfile
  Podfile.lock
  WordPressKit.podspec
Labels: releases

#237 Release/4.6.0
  .ruby-version
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKit.xcscheme
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKitTests.xcscheme
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/AtomicAuthenticationServiceRemote.swift
  WordPressKit/CocoaLumberjack.swift
  WordPressKit/MediaServiceRemote.h
  WordPressKit/MediaServiceRemoteREST.m
  WordPressKit/MediaServiceRemoteXMLRPC.m
  WordPressKit/PluginDirectoryEntry.swift
  WordPressKit/RemotePlan_ApiVersion1_3.swift
  WordPressKit/WordPressComOAuthClient.swift
  WordPressKit/WordPressOrgXMLRPCValidator.swift
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/AtomicAuthenticationServiceRemoteTests.swift
  WordPressKitTests/BlogServiceRemoteRESTTests.m
  WordPressKitTests/MediaServiceRemoteRESTTests.swift
  WordPressKitTests/Mock Data/atomic-get-auth-cookie-success.json
  WordPressKitTests/Mock Data/site-plans-v3-success.json
  WordPressKitTests/ReaderSiteServiceRemoteTests.swift
  WordPressKitTests/RemoteTestCase.swift
  WordPressKitTests/WordPressComOAuthTests.swift
  WordPressKitTests/WordPressComRestApiTests.swift
  WordPressKitTests/WordPressComServiceRemoteRestTests.swift
  WordPressKitTests/WordPressOrgXMLRPCApiTests.swift
Labels: releases

#202 [PoC] WP-API and Cookie Authentication
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Authenticator.swift
  WordPressKit/WordPressOrgRestApi.swift
  WordPressKitTests/AuthenticatorTests.swift
  WordPressKitTests/Mock Data/wp-admin-post-new.html
  WordPressKitTests/Mock Data/wp-forbidden.json
  WordPressKitTests/Mock Data/wp-pages.json
  WordPressKitTests/WordPressOrgRestApiTests.swift
Labels: enhancement
