Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2020-11, with the labels that each got.

#298 Merge 4.20 into trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/PageLayoutServiceRemote.swift
  WordPressKit/RemotePageLayouts.swift
  WordPressKitTests/Mock Data/page-layout-blog-layouts-malformed.json
  WordPressKitTests/Mock Data/page-layout-blog-layouts-success.json
  WordPressKitTests/PageLayoutServiceRemoteTests.swift
Labels: releases

#297 [Home Page Picker] Adds nux/starter-designs endpoint
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/RemoteSiteDesign.swift
  WordPressKit/SiteDesignServiceRemote.swift
  WordPressKitTests/Mock Data/nux-starter-designs-malformed.json
  WordPressKitTests/Mock Data/nux-starter-designs-success.json
  WordPressKitTests/SiteDesignServiceRemoteTests.swift
Labels: enhancement

#299 [Home Page Picker] Modify site creation flow to support creating sites by selecting a design
  WordPressKit.podspec
  WordPressKit/RemoteSiteDesign.swift
  WordPressKit/SiteDesignServiceRemote.swift
  WordPressKit/WordPressComServiceRemote+SiteCreation.swift
  WordPressKitTests/Mock Data/nux-starter-designs-success.json
  WordPressKitTests/SiteCreationRequestEncodingTests.swift
  WordPressKitTests/WordPressComServiceRemoteTests+SiteCreation.swift
Labels: enhancement

#303 Merge `4.21.0` into trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/ActivityServiceRemote.swift
  WordPressKit/RemoteSiteDesign.swift
  WordPressKit/SiteDesignServiceRemote.swift
  WordPressKit/WordPressComServiceRemote+SiteCreation.swift
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/Mock Data/nux-starter-designs-malformed.json
  WordPressKitTests/Mock Data/nux-starter-designs-success.json
  WordPressKitTests/SiteCreationRequestEncodingTests.swift
  WordPressKitTests/SiteDesignServiceRemoteTests.swift
  WordPressKitTests/WordPressComServiceRemoteTests+SiteCreation.swift
Labels: releases

#304 Adds in Jetpack Scan API with models
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Decodable+Dictionary.swift
  WordPressKit/Enum+UnknownCaseRepresentable.swift
  WordPressKit/JSONDecoderExtension.swift
  WordPressKit/Jetpack Scan/JetpackCredentials.swift
  WordPressKit/Jetpack Scan/JetpackScan.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/JetpackScanServiceRemote.swift
  WordPressKitTests/Mock Data/jetpack-scan-enqueue-failure.json
  WordPressKitTests/Mock Data/jetpack-scan-enqueue-success.json
  WordPressKitTests/Mock Data/jetpack-scan-idle-success-no-threats.json
  WordPressKitTests/Mock Data/jetpack-scan-idle-success-threats.json
  WordPressKitTests/Mock Data/jetpack-scan-in-progress.json
  WordPressKitTests/Mock Data/jetpack-scan-unavailable.json
  WordPressKitTests/Scan/JetpackScanServiceRemoteTests.swift
Labels: enhancement

#305 Makes PluginState.directoryURL and optional to fix a crash.
  WordPressKit.podspec
  WordPressKit/PluginState.swift
Labels: bug

#307 Merge 4.22 into trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/ActivityServiceRemote.swift
  WordPressKit/Decodable+Dictionary.swift
  WordPressKit/Enum+UnknownCaseRepresentable.swift
  WordPressKit/JSONDecoderExtension.swift
  WordPressKit/Jetpack Scan/JetpackCredentials.swift
  WordPressKit/Jetpack Scan/JetpackScan.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/JetpackScanServiceRemote.swift
  WordPressKit/PluginState.swift
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/Mock Data/jetpack-scan-enqueue-failure.json
  WordPressKitTests/Mock Data/jetpack-scan-enqueue-success.json
  WordPressKitTests/Mock Data/jetpack-scan-idle-success-no-threats.json
  WordPressKitTests/Mock Data/jetpack-scan-idle-success-threats.json
  WordPressKitTests/Mock Data/jetpack-scan-in-progress.json
  WordPressKitTests/Mock Data/jetpack-scan-unavailable.json
  WordPressKitTests/Scan/JetpackScanServiceRemoteTests.swift
Labels: releases
