Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2020-12, with the labels that each got.

#310 Add a property (isWPForTeams) to a remote model (RemoteReaderSiteInfo)
  WordPressKit.podspec
  WordPressKit/RemoteReaderSiteInfo.h
  WordPressKit/RemoteReaderSiteInfo.m
Labels: enhancement

#312 Support for Reader P2 menu option
  WordPressKit.podspec
  WordPressKit/ReaderTopicServiceRemote.m
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
Labels: enhancement

#313 Reader: update to use site's organization_id
  WordPressKit.podspec
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKit/RemoteReaderSiteInfo.h
  WordPressKit/RemoteReaderSiteInfo.m
Labels: enhancement

#315 Cut 4.23.0
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Activity.swift
  WordPressKit/ActivityServiceRemote.swift
  WordPressKit/Date+endOfDay.swift
  WordPressKit/Jetpack Scan/JetpackCredentials.swift
  WordPressKit/Jetpack Scan/JetpackScan.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/ReaderTopicServiceRemote.m
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKit/RemoteReaderSiteInfo.h
  WordPressKit/RemoteReaderSiteInfo.m
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/Mock Data/activity-groups-bad-json-failure.json
  WordPressKitTests/Mock Data/activity-groups-success.json
Labels: releases

#314 Adds optional parameter for quantity to Domain Suggestion service
  WordPressKit.podspec
  WordPressKit/DomainsServiceRemote.swift
Labels: enhancement

#317 Bump pod version.
  WordPressKit.podspec
Labels: releases

#319 Map `unseen_count` field to `RemoteReaderSiteInfo`
  WordPressKit.podspec
  WordPressKit/RemoteReaderSiteInfo.h
  WordPressKit/RemoteReaderSiteInfo.m
Labels: enhancement

#320 Increases endpoint version for login with email. Improves Jetpack-connect support.
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
Labels: bug
