Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2020-08, with the labels that each got.

#267 Fix error when toggling Jetpack security settings.
  WordPressKit.podspec
  WordPressKit/BlogJetpackSettingsServiceRemote.swift
Labels: Jetpack

#272 Merge 4.15 into main
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BlogJetpackSettingsServiceRemote.swift
  WordPressKit/Decodable+Dictionary.swift
  WordPressKit/DomainContactInformation.swift
  WordPressKit/Info.plist
  WordPressKit/ReaderPostServiceRemote+Cards.swift
  WordPressKit/ReaderPostServiceRemote+Subscriptions.swift
  WordPressKit/ReaderPostServiceRemote.m
  WordPressKit/ReaderTopicServiceRemote+Interests.swift
  WordPressKit/RemoteBlogOptionsHelper.m
  WordPressKit/RemoteReaderCard.swift
  WordPressKit/RemoteReaderInterest.swift
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKit/WordPressComRestApi.swift
  WordPressKit/WordPressOrgXMLRPCApi.swift
  WordPressKitTests/Extensions/Decodable+DictionaryTests.swift
  WordPressKitTests/Mock Data/reader-cards-success.json
  WordPressKitTests/Mock Data/reader-interests-success.json
  WordPressKitTests/Mock Data/reader-post-comments-subscribe-success.json
  WordPressKitTests/Mock Data/reader-post-comments-subscription-status-success.json
  WordPressKitTests/Mock Data/reader-post-comments-unsubscribe-success.json
  WordPressKitTests/ReaderPostServiceRemote+CardsTests.swift
  WordPressKitTests/ReaderPostServiceRemote+SubscriptionTests.swift
  WordPressKitTests/ReaderPostServiceRemoteTests.m
  WordPressKitTests/ReaderTopicServiceRemote+InterestsTests.swift
  WordPressKitTests/RemoteReaderPostTests.m
Labels: releases

#268 Add missing properties to `RemoteGravatarProfile`
  WordPressKit.podspec
  WordPressKit/GravatarServiceRemote.swift
  WordPressKit/RemoteGravatarProfile.swift
Labels: enhancement

#270 Add support for fetching remote feature flags
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/FeatureFlag.swift
  WordPressKit/FeatureFlagRemote.swift
  WordPressKitTests/Utilities/FeatureFlagRemoteTests.swift
Labels: enhancement

#274 expose siteID read-only property in StatsServiceRemoteV2
  WordPressKit.podspec
  WordPressKit/StatsServiceRemoteV2.swift
Labels: bug
