Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2020-09, with the labels that each got.

#273 Big Fixes for FeatureFlag implementation
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/FeatureFlag.swift
  WordPressKit/FeatureFlagRemote.swift
  WordPressKitTests/Utilities/FeatureFlagRemoteTests.swift
  WordPressKitTests/Utilities/FeatureFlagSerializationTest.swift
Labels: bug

#276 Adds remote feature announcements service
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AnnouncementServiceRemote.swift
  WordPressKit/WordPressComRestApi.swift
Labels: enhancement

#277 Merge 4.15.1 into main
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKit.xcscheme
  WordPressKit/FeatureFlag.swift
  WordPressKit/FeatureFlagRemote.swift
  WordPressKit/GravatarServiceRemote.swift
  WordPressKit/PluginDirectoryEntry.swift
  WordPressKit/PluginDirectoryFeedPage.swift
  WordPressKit/PluginDirectoryServiceRemote.swift
  WordPressKit/PluginServiceRemote.swift
  WordPressKit/PluginState.swift
  WordPressKit/RemoteGravatarProfile.swift
  WordPressKit/StatsServiceRemoteV2.swift
  WordPressKitTests/AuthenticatorTests.swift
  WordPressKitTests/DynamicMockProvider.swift
  WordPressKitTests/Mock Data/plugin-directory-jetpack-beta.json
  WordPressKitTests/Mock Data/plugin-install-already-installed.json
  WordPressKitTests/Mock Data/plugin-install-generic-error.json
  WordPressKitTests/Mock Data/plugin-install-succeeds.json
  WordPressKitTests/Mock Data/plugin-modify-malformed-response.json
  WordPressKitTests/Mock Data/plugin-service-remote-auth-failure.json
  WordPressKitTests/Mock Data/plugin-service-remote-featured-malformed.json
  WordPressKitTests/Mock Data/plugin-service-remote-featured-plugins-invalid.json
  WordPressKitTests/Mock Data/plugin-service-remote-featured.json
  WordPressKitTests/Mock Data/plugin-state-contact-form-7.json
  WordPressKitTests/Mock Data/plugin-state-jetpack.json
  WordPressKitTests/Mock Data/plugin-update-gutenberg-needs-update.json
  WordPressKitTests/Mock Data/plugin-update-jetpack-already-updated.json
  WordPressKitTests/Mock Data/plugin-update-response-malformed.json
  WordPressKitTests/Mock Data/site-plugins-malformed.json
  WordPressKitTests/Mock Data/site-plugins-success.json
  WordPressKitTests/MockPluginDirectoryEntryProvider.swift
  WordPressKitTests/MockPluginStateProvider.swift
  WordPressKitTests/PluginDirectoryTests.swift
  WordPressKitTests/PluginServiceRemoteTests.swift
  WordPressKitTests/PluginStateTests.swift
  WordPressKitTests/SitePluginTests.swift
  WordPressKitTests/Utilities/FeatureFlagRemoteTests.swift
Labels: releases

#281 Merge release/4.16.0 back into develop
  WordPressKit.podspec
Labels: releases

#282 Release/4.16
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/AnnouncementServiceRemote.swift
  WordPressKit/FeatureFlag.swift
  WordPressKit/FeatureFlagRemote.swift
  WordPressKit/WordPressComRestApi.swift
  WordPressKitTests/Utilities/FeatureFlagRemoteTests.swift
  WordPressKitTests/Utilities/FeatureFlagSerializationTest.swift
Labels: releases

#279 Update Announcement and Feature types to Codable to allow plist encoding
  WordPressKit.podspec
  WordPressKit/AnnouncementServiceRemote.swift
Labels: enhancement

#283 Prevent triggering lazy property initialization on deinitialization
  WordPressKit.podspec
  WordPressKit/WordPressOrgXMLRPCApi.swift
Labels: bug

#280 Upgrade Xcode to 12.0
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKit.xcscheme
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKitTests.xcscheme
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.h
  WordPressKit/BlogServiceRemoteREST.h
  WordPressKit/BlogServiceRemoteXMLRPC.h
  WordPressKit/CommentServiceRemote.h
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteXMLRPC.h
  WordPressKit/MediaServiceRemoteREST.h
  WordPressKit/MediaServiceRemoteXMLRPC.h
  WordPressKit/MenusServiceRemote.h
  WordPressKit/PostServiceRemote.h
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteXMLRPC.h
  WordPressKit/ReaderPostServiceRemote.h
  WordPressKit/ReaderSiteServiceRemote.h
  WordPressKit/ReaderTopicServiceRemote.h
  WordPressKit/SiteServiceRemoteWordPressComREST.h
  WordPressKit/TaxonomyServiceRemoteREST.h
  WordPressKit/TaxonomyServiceRemoteXMLRPC.h
  WordPressKit/ThemeServiceRemote.h
  WordPressKit/WordPressComServiceRemote.h
  WordPressKit/WordPressKit.h
  WordPressKit/WordPressOrgXMLRPCApi.swift
Labels: enhancement

#285 Release 4.17.0
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKit.xcscheme
  WordPressKit.xcodeproj/xcshareddata/xcschemes/WordPressKitTests.xcscheme
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.h
  WordPressKit/AnnouncementServiceRemote.swift
  WordPressKit/BlogServiceRemoteREST.h
  WordPressKit/BlogServiceRemoteXMLRPC.h
  WordPressKit/CommentServiceRemote.h
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteXMLRPC.h
  WordPressKit/MediaServiceRemoteREST.h
  WordPressKit/MediaServiceRemoteXMLRPC.h
  WordPressKit/MenusServiceRemote.h
  WordPressKit/PostServiceRemote.h
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteXMLRPC.h
  WordPressKit/ReaderPostServiceRemote.h
  WordPressKit/ReaderSiteServiceRemote.h
  WordPressKit/ReaderTopicServiceRemote.h
  WordPressKit/SiteServiceRemoteWordPressComREST.h
  WordPressKit/TaxonomyServiceRemoteREST.h
  WordPressKit/TaxonomyServiceRemoteXMLRPC.h
  WordPressKit/ThemeServiceRemote.h
  WordPressKit/WordPressComServiceRemote.h
  WordPressKit/WordPressKit.h
  WordPressKit/WordPressOrgXMLRPCApi.swift
Labels: releases

#287 Add support for base64 images in Feature
  WordPressKit.podspec
  WordPressKit/AnnouncementServiceRemote.swift
Labels: bug
