Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-04, with the labels that each got.

#378 Merge 4.30.0 into trunk
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
Labels: releases

#379 Likes: remove parsing user's URL
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser.h
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: [Type] Task

#383 Adds a wrapper around the dotCom and Dot Org Rest API
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/WordPressComRestApi.swift
  WordPressKit/WordPressOrgRestApi.swift
  WordPressKit/WordPressRestApi.swift
  WordPressKitTests/WordPressComRestApiTests.swift
Labels: [Type] Task, enhancement

#384 Merge 4.31.0 into trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AppTransportSecuritySettings.swift
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser.h
  WordPressKit/WordPressComRestApi.swift
  WordPressKit/WordPressOrgRestApi.swift
  WordPressKit/WordPressOrgXMLRPCValidator.swift
  WordPressKit/WordPressRestApi.swift
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Fakes/FakeInfoDictionaryObjectProvider.swift
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Utilities/AppTransportSecuritySettingsTests.swift
  WordPressKitTests/WordPressAPI/WordPressOrgXMLRPCValidatorTests.swift
  WordPressKitTests/WordPressComRestApiTests.swift
Labels: releases

#387 Parse a remote user's email response.
  WordPressKit.podspec
  WordPressKit/BlogServiceRemoteXMLRPC.m
Labels: enhancement

#389 Likes: update endpoint version and parse new data
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser+Likes.swift
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/comment-likes-success.json
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
  WordPressKitTests/WordPressAPI/WordPressOrgXMLRPCValidatorTests.swift
  WordPressKitTests/WordPressComRestApiTests.swift
Labels: enhancement

#390 Add the edit context to the delete post call
  WordPressKit.podspec
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/PostServiceRemoteRESTTests.m
Labels: bug

#391 RemoteLikeUserPreferredBlog: make properties public
  WordPressKit.podspec
  WordPressKit/RemoteUser+Likes.swift
Labels: enhancement

#392 Comment and Post likes: get relevant IDs
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser+Likes.swift
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement
