Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-03, with the labels that each got.

#358 Remove testing log messages
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/CommentServiceRemoteXMLRPC.m
Labels: [Type] Task

#352 Update site design models and service for new API endpoint
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/RemoteSiteDesign.swift
  WordPressKit/SiteDesignServiceRemote.swift
  WordPressKitTests/Mock Data/common-starter-site-designs-empty-designs.json
  WordPressKitTests/Mock Data/common-starter-site-designs-malformed.json
  WordPressKitTests/Mock Data/common-starter-site-designs-success.json
  WordPressKitTests/Mock Data/nux-starter-designs-malformed.json
  WordPressKitTests/Mock Data/nux-starter-designs-success.json
  WordPressKitTests/SiteDesignServiceRemoteTests.swift
Labels: enhancement

#361 Add home URL to RemoteUser
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser.h
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/comment-likes-success.json
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement

#364 Add support to fetch likes for posts and comments
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/RemoteUser.h
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/comment-likes-success.json
  WordPressKitTests/Mock Data/post-likes-failure.json
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement

#369 Add property to Account Settings: user enabled block emails
  WordPressKit.podspec
  WordPressKit/AccountSettings.swift
  WordPressKit/AccountSettingsRemote.swift
  WordPressKitTests/AccountSettingsRemoteTests.swift
  WordPressKitTests/me-settings-success.json
Labels: enhancement

#370 Changes the PluginDirectoryEntry.rating property to a Double
  WordPressKit.podspec
  WordPressKit/PluginDirectoryEntry.swift
  WordPressKitTests/Mock Data/plugin-directory-jetpack-beta.json
  WordPressKitTests/Mock Data/plugin-directory-jetpack.json
  WordPressKitTests/Mock Data/plugin-directory-new.json
  WordPressKitTests/Mock Data/plugin-directory-popular.json
  WordPressKitTests/Mock Data/plugin-directory-rename-xml-rpc.json
  WordPressKitTests/Mock Data/plugin-service-remote-featured.json
Labels: [Type] Task, bug

#372 Merge the changes from 4.28.1 into develop
  WordPressKit.podspec
  WordPressKit/PluginDirectoryEntry.swift
  WordPressKitTests/Mock Data/plugin-directory-jetpack-beta.json
  WordPressKitTests/Mock Data/plugin-directory-jetpack.json
  WordPressKitTests/Mock Data/plugin-directory-new.json
  WordPressKitTests/Mock Data/plugin-directory-popular.json
  WordPressKitTests/Mock Data/plugin-directory-rename-xml-rpc.json
  WordPressKitTests/Mock Data/plugin-service-remote-featured.json
Labels: [Type] Task

#371 Last Post Insight: don't fail if there are no posts
  WordPressKit.podspec
  WordPressKit/StatsServiceRemoteV2.swift
  WordPressKitTests/ReaderPostServiceRemote+RelatedPostsTests.swift
Labels: bug

#365 Add device mode selection for page layouts
  WordPressKit.podspec
  WordPressKit/RemotePageLayouts.swift
Labels: enhancement
