Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-06, with the labels that each got.

#403 pass on the statusCode if one exists
  WordPressKit.podspec
  WordPressKit/WordPressOrgXMLRPCApi.swift
Labels: bug

#408 Merge 4.35.0 into trunk
  WordPressKit.podspec
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/WordPressOrgXMLRPCApi.swift
Labels: releases

#409 Issues/16599 add new reader post fields
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
Labels: enhancement

#406 Expose some methods to use in WPiOS Plugin Management
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Plugin Management/JetpackPluginManagementClient.swift
  WordPressKit/Plugin Management/PluginManagementClient.swift
  WordPressKit/Plugin Management/SelfHostedPluginManagementClient.swift
  WordPressKit/PluginServiceRemote.swift
  WordPressKit/SitePlugin.swift
  WordPressKit/WordPressOrgRestApi.swift
  WordPressKitTests/PluginServiceRemoteTests.swift
Labels: enhancement

#410 Merge 4.36.0 into trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Plugin Management/JetpackPluginManagementClient.swift
  WordPressKit/Plugin Management/PluginManagementClient.swift
  WordPressKit/Plugin Management/SelfHostedPluginManagementClient.swift
  WordPressKit/PluginServiceRemote.swift
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKit/SitePlugin.swift
  WordPressKit/WordPressOrgRestApi.swift
  WordPressKitTests/PluginServiceRemoteTests.swift
Labels: releases

#411 Removed unnecessary `@objc` annotations from `Country` and `State` entities
  WordPressKit.podspec
  WordPressKit/Country.swift
  WordPressKit/State.swift
Labels: good first issue

#412 Renamed Country and State entities to `WPCountry` and `WPState`
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/DomainsServiceRemote.swift
  WordPressKit/TransactionsServiceRemote.swift
  WordPressKit/WPCountry.swift
  WordPressKit/WPState.swift
Labels: bug, good first issue

#413 Comments: update Comment fetching and parsing
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/Plugin Management/SelfHostedPluginManagementClient.swift
  WordPressKit/RemoteComment.h
Labels: enhancement
