Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-02, with the labels that each got.

#341 RemoteReaderPost: add isSeenSupported property
  WordPressKit.podspec
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
Labels: enhancement

#342 Jetpack Section: Adds scan fixing status
  WordPressKit.podspec
  WordPressKit/Jetpack Scan/JetpackScan.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/Jetpack Scan/JetpackThreatFixStatus.swift
Labels: [Type] Task

#345 Release 4.26.0 -> trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/ActivityServiceRemote_ApiVersion1_0.swift
  WordPressKit/Jetpack Scan/JetpackScan.swift
  WordPressKit/Jetpack Scan/JetpackScanHistory.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/Jetpack Scan/JetpackThreatFixStatus.swift
  WordPressKit/JetpackBackupServiceRemote.swift
  WordPressKit/JetpackScanServiceRemote.swift
  WordPressKit/ReaderPostServiceRemote+V2.swift
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKit/RemoteSiteDesign.swift
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/JetpackBackupServiceRemoteTests.swift
  WordPressKitTests/Mock Data/backup-get-backup-status-complete-without-download-id-success.json
Labels: releases

#347 Implementation for post likes endpoint
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/Mock Data/post-likes-failure.json
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement

#348 Fix unit test timezone issue in local machine
  WordPressKitTests/StatsRemoteV2Tests.swift
Labels: bug

#350 Comments: allow fetching by status
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/CommentServiceRemoteXMLRPC.m
Labels: enhancement

#351 Implementation for comment likes endpoint
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/comment-likes-success.json
Labels: enhancement

#354 Following a conversation: handle success: false
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/ReaderPostServiceRemote+Subscriptions.swift
  WordPressKitTests/Mock Data/reader-post-comments-subscribe-failure.json
  WordPressKitTests/ReaderPostServiceRemote+SubscriptionTests.swift
Labels: enhancement

#355 Merge 4.27 into trunk
  Podfile
  Podfile.lock
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/CommentServiceRemoteXMLRPC.m
  WordPressKit/ReaderPostServiceRemote+Cards.swift
  WordPressKitTests/ReaderPostServiceRemote+CardsTests.swift
  WordPressKitTests/StatsRemoteV2Tests.swift
Labels: releases

#357 Comments: determine which 'status' parameter to use based on provided status.
  WordPressKit.podspec
  WordPressKit/CommentServiceRemote.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/CommentServiceRemoteXMLRPC.m
Labels: enhancement

#356 Feature/invite links
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/PeopleServiceRemote.swift
  WordPressKit/RemoteInviteLink.swift
  WordPressKitTests/Mock Data/sites-invites-links-disable-empty.json
  WordPressKitTests/Mock Data/sites-invites-links-disable.json
  WordPressKitTests/Mock Data/sites-invites-links-generate.json
  WordPressKitTests/Mock Data/sites-invites.json
  WordPressKitTests/PeopleServiceRemoteTests.swift
Labels: enhancement
