Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-09, with the labels that each got.

#440 Comment update: add additional fields to update
  WordPressKit.podspec
  WordPressKit/AccountSettingsRemote.swift
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/CommentServiceRemoteXMLRPC.m
  WordPressKitTests/AccountSettingsRemoteTests.swift
Labels: enhancement

#439 Remove CircleCI
  .buildkite/pipeline.yml
  .circleci/config.yml
  README.md
Labels: enhancement

#417 [Gutenberg] Pass the Gallery v2 Flag over from the editor
  WordPressKit.podspec
  WordPressKit/RemoteBlockEditorSettings.swift
Labels: enhancement

#443 Merge trial/nikola milicevic changes into develop
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/StatsServiceRemoteV2.swift
  WordPressKit/Time Interval/StatsTopReferrersTimeIntervalData.swift
  WordPressKitTests/Mock Data/stats-referrer-mark-as-spam.json
  WordPressKitTests/StatsRemoteV2Tests.swift
Labels: enhancement

#444 Add the option to create a persistent cart for domains
  WordPressKit.podspec
  WordPressKit/TransactionsServiceRemote.swift
Labels: [Type] Task

#445 Adds organization IDs to blogs.
  WordPressKit.podspec
  WordPressKit/RemoteBlog.h
  WordPressKit/RemoteBlog.m
Labels: enhancement

#446 Reader cross post parsing: fix post url format
  WordPressKit.podspec
  WordPressKit/RemoteReaderPost.m
Labels: bug

#447 Merge 4.42.0 stable version bump into `develop`
  WordPressKit.podspec
Labels: releases
