Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-05, with the labels that each got.

#396 Merge 4.32.0 to trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BlogServiceRemoteXMLRPC.m
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKit/PostServiceRemoteXMLRPC.m
  WordPressKit/RemoteUser+Likes.swift
  WordPressKit/SiteDesignServiceRemote.swift
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/Mock Data/comment-likes-success.json
  WordPressKitTests/Mock Data/post-likes-success.json
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTTests.m
  WordPressKitTests/WordPressAPI/WordPressOrgXMLRPCValidatorTests.swift
  WordPressKitTests/WordPressComRestApiTests.swift
Labels: releases

#395 Merge 4.32.0 to develop
  WordPressKit.podspec
Labels: releases

#400 Add pagination support to Post and Comment Likes endpoints.
  .circleci/config.yml
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement

#399 Merge 4.33.0 into trunk
  WordPressKit.podspec
  WordPressKit/AccountServiceRemoteREST.m
Labels: releases

#401 Specify pointer nullability types
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.h
  WordPressKitTests/PostServiceRemoteRESTTests.m
Labels: [Type] Task

#402 Likes: add ability to exclude user IDs from Likes responses.
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
Labels: enhancement

#404 Merge 4.34.0 into trunk
  .circleci/config.yml
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.h
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/PostServiceRemoteREST.h
  WordPressKit/PostServiceRemoteREST.m
  WordPressKitTests/CommentServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTLikesTests.swift
  WordPressKitTests/PostServiceRemoteRESTTests.m
Labels: releases
