Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-07, with the labels that each got.

#394 [Global Styles] Implement Global Styles endpoint
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BlockEditorSettingsServiceRemote.swift
  WordPressKit/ChecksumUtil.swift
  WordPressKit/RemoteBlockEditorSettings.swift
  WordPressKitTests/BlockEditorSettingsServiceRemoteTests.swift
  WordPressKitTests/Mock Data/BlockEditorSettings/get_wp_v2_themes_twentytwentyone-no-colors.json
  WordPressKitTests/Mock Data/BlockEditorSettings/get_wp_v2_themes_twentytwentyone.json
  WordPressKitTests/Mock Data/BlockEditorSettings/wp-block-editor-v1-settings-success-NotThemeJSON.json
  WordPressKitTests/Mock Data/BlockEditorSettings/wp-block-editor-v1-settings-success-ThemeJSON.json
  WordPressKitTests/Utilities/ChecksumUtilTests.swift
Labels: enhancement

#415 Add reason property to JetpackScan
  WordPressKit.podspec
  WordPressKit/Jetpack Scan/JetpackScan.swift
Labels: Jetpack

#414 Add Zendesk metadata to PlanServiceRemote
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Plans/PlanServiceRemote.swift
  WordPressKit/Plans/PlanServiceRemote_ApiVersion1_3.swift
  WordPressKit/ZendeskMetadata.swift
Labels: enhancement

#416 Update Global Styles endpoint to support non-experimental paths
  WordPressKit.podspec
  WordPressKit/BlockEditorSettingsServiceRemote.swift
  WordPressKit/WordPressComRestApi.swift
  WordPressKitTests/BlockEditorSettingsServiceRemoteTests.swift
  WordPressKitTests/MockWordPressComRestApi.swift
  WordPressKitTests/WordPressComRestApiTests.swift
Labels: enhancement

#421 Merge release 4.37.1 into develop
  WordPressKit.podspec
  WordPressKit/CommentServiceRemoteREST.m
  WordPressKit/RemoteComment.h
Labels: releases

#424 Issue/domain registration cart
  WordPressKit.podspec
  WordPressKit/TransactionsServiceRemote.swift
Labels: bug

#425 Add Buildkite CI
  .buildkite/build-and-test.sh
  .buildkite/lint.sh
  .buildkite/pipeline.yml
  .buildkite/validate-podspec.sh
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPressKit.podspec
  fastlane/Fastfile
Labels: enhancement
