Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2021-01, with the labels that each got.

#322 Fixes magic links.
  WordPressKit.podspec
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
Labels: bug

#324 Merge release/4.24.0 -> trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/AccountServiceRemote.h
  WordPressKit/AccountServiceRemoteREST.h
  WordPressKit/AccountServiceRemoteREST.m
  WordPressKit/ActivityServiceRemote_ApiVersion1_0.swift
  WordPressKit/DomainsServiceRemote.swift
  WordPressKit/JetpackBackup.swift
  WordPressKit/JetpackBackupServiceRemote.swift
  WordPressKit/JetpackRestoreTypes.swift
  WordPressKit/ReaderTopicServiceRemote.m
  WordPressKit/RemoteReaderSiteInfo.h
  WordPressKit/RemoteReaderSiteInfo.m
  WordPressKit/RemoteReaderTopic.h
  WordPressKitTests/AccountServiceRemoteRESTTests.swift
  WordPressKitTests/ActivityServiceRemoteTests.swift
  WordPressKitTests/JetpackBackupServiceRemoteTests.swift
  WordPressKitTests/backup-get-backup-status-complete-success.json
  WordPressKitTests/backup-get-backup-status-in-progress-success.json
  WordPressKitTests/backup-prepare-backup-success.json
Labels: releases

#323 Merge release/4.24.0 -> develop
  WordPressKit.podspec
Labels: releases

#325 Add memberwise public init for JetpackRestoreTypes
  WordPressKit.podspec
  WordPressKit/JetpackRestoreTypes.swift
Labels: [Type] Task

#327 Add support for marking Reader posts seen/unseen
  WordPressKit.podspec
  WordPressKit/ReaderPostServiceRemote+V2.swift
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
Labels: enhancement

#328 Add current entry for Restore Status
  WordPressKit.podspec
  WordPressKit/Activity.swift
Labels: [Type] Task

#329 Jetpack Section: Adds Fix All / Fix Single / Get Status API calls
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/Jetpack Scan/JetpackThreatFixStatus.swift
  WordPressKit/JetpackScanServiceRemote.swift
Labels: Jetpack, [Type] Task

#334 Release 4.25.0 -> develop
  WordPressKit.podspec
Labels: releases

#335 Release 4.25.0 -> trunk
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Activity.swift
  WordPressKit/Jetpack Scan/JetpackScanThreat.swift
  WordPressKit/Jetpack Scan/JetpackThreatFixStatus.swift
  WordPressKit/JetpackCapabilitiesServiceRemote.swift
  WordPressKit/JetpackRestoreTypes.swift
  WordPressKit/JetpackScanServiceRemote.swift
  WordPressKit/ReaderPostServiceRemote+V2.swift
  WordPressKit/RemoteReaderPost.h
  WordPressKit/RemoteReaderPost.m
  WordPressKitTests/JetpackCapabilitiesServiceRemoteTests.swift
  WordPressKitTests/Mock Data/jetpack-capabilities-107159616-success.json
  WordPressKitTests/Mock Data/jetpack-capabilities-34197361-success.json
  WordPressKitTests/Mock Data/jetpack-capabilities-malformed.json
Labels: releases

#331 Jetpack Section: Adds scan history APIs
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Jetpack Scan/JetpackScanHistory.swift
  WordPressKit/JetpackScanServiceRemote.swift
Labels: [Type] Task

#336 Reader seen toggle: Separate methods to toggle by feedItemID or postID.
  WordPressKit.podspec
  WordPressKit/ReaderPostServiceRemote+V2.swift
Labels: enhancement

#330 Add mobile and tablet screenshots to remote site design
  WordPressKit.podspec
  WordPressKit/RemoteSiteDesign.swift
Labels: enhancement
