Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2022-10, with the labels that each got.

#542 Merge 4.58.0 stable release
  WordPressKit.podspec
Labels: releases

#543 Stats Revamp: AnnualAntMostPopularTime percentages are always rounded down
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/Insights/StatsAnnualAndMostPopularTimeInsight.swift
  WordPressKitTests/StatsAnnualAndMostPopularTimeInsightDecodingTests.swift
Labels: bug

#544 Merge 4.58.1 stable release
  WordPressKit.podspec
Labels: releases

#547 Add support for fetching remote config values
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/RemoteConfigRemote.swift
  WordPressKitTests/Utilities/RemoteConfigRemoteTests.swift
Labels: [Type] Task
