Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2022-05, with the labels that each got.

#496 Add remote service for Blogging Prompts
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BloggingPromptsServiceRemote.swift
  WordPressKit/RemoteBloggingPrompt.swift
  WordPressKitTests/BloggingPromptsServiceRemoteTests.swift
  WordPressKitTests/Mock Data/blogging-prompts-success.json
Labels: enhancement

#499 Add featured image URL to StatsLastPostInsight
  WordPressKit.podspec
  WordPressKit/Insights/StatsLastPostInsight.swift
Labels: enhancement

#501 Add attribution field to blogging prompts
  WordPressKit.podspec
  WordPressKit/RemoteBloggingPrompt.swift
  WordPressKitTests/BloggingPromptsServiceRemoteTests.swift
  WordPressKitTests/Mock Data/blogging-prompts-success.json
Labels: enhancement

#497 Update CartResponse CartKey return type to fix parse failure
  Podfile.lock
  WordPressKit.podspec
  WordPressKit/TransactionsServiceRemote.swift
Labels: bug

#505 Fix date component timezone in blogging prompts unit test
  WordPressKit.podspec
  WordPressKitTests/BloggingPromptsServiceRemoteTests.swift
Labels: bug

#507 [Site Design Revamp] Add optional group array for remote site designs
  WordPressKit/RemoteSiteDesign.swift
Labels: enhancement

#504 Add endpoints for blogging prompts settings
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BloggingPromptsServiceRemote.swift
  WordPressKit/RemoteBlogOptionsHelper.m
  WordPressKit/RemoteBloggingPromptsSettings.swift
  WordPressKitTests/BloggingPromptsServiceRemoteTests.swift
  WordPressKitTests/Mock Data/blogging-prompts-settings-fetch-success.json
  WordPressKitTests/Mock Data/blogging-prompts-settings-update-empty-response.json
  WordPressKitTests/Mock Data/blogging-prompts-settings-update-with-response.json
Labels: enhancement

#508 Adds the beta group in the available design groups enumeration
  WordPressKit.podspec
  WordPressKit/SiteDesignServiceRemote.swift
Labels: enhancement, [Status] DO NOT MERGE

#511 Add public initializers to `RemoteBloggingPromptsSettings` & `ReminderDays`
  WordPressKit.podspec
  WordPressKit/RemoteBloggingPromptsSettings.swift
Labels: enhancement
