Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2023-11, with the labels that each got.

#640 Add tag parameter (again)
  CHANGELOG.md
  WordPressKit.podspec
  WordPressKit/PostServiceRemoteOptions.h
  WordPressKit/PostServiceRemoteREST.m
Labels: [Type] Task

#641 Use Xcode 15.0.1
  .buildkite/pipeline.yml
Labels: enhancement

#642 Add transfer case to DomainType enum
  CHANGELOG.md
  WordPressKit/RemoteDomain.swift
Labels: enhancement, [Type] Task

#644 Add support for no-site carts
  CHANGELOG.md
  WordPressKit/TransactionsServiceRemote.swift
Labels: enhancement, [Type] Task
