Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2023-02, with the labels that each got.

#573 Add jetpack_connection_active_plugins to RemoteBlog options
  WordPressKit.podspec
  WordPressKit/RemoteBlogOptionsHelper.swift
Labels: Jetpack

#576 Add Jetpack Proxy remote service
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/JetpackProxyServiceRemote.swift
  WordPressKitTests/JetpackProxyServiceRemoteTests.swift
Labels: enhancement, Jetpack

#577 Add blaze status endpoint
  WordPressKit.podspec
  WordPressKit.xcodeproj/project.pbxproj
  WordPressKit/BlazeServiceRemote.swift
  WordPressKitTests/BlazeServiceRemoteTests.swift
Labels: [Type] Task
