Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2024-06, with the labels that each got.

#810 Adds os_version parameter to feature flags and dashboard cards APIs
  Sources/WordPressKit/Models/SessionDetails.swift
  Tests/WordPressKitTests/Tests/DashboardServiceRemoteTests.swift
  Tests/WordPressKitTests/Tests/Utilities/FeatureFlagRemoteTests.swift
Labels: enhancement, [Status] DO NOT MERGE

#811 Bump version to 17.2.0
  CHANGELOG.md
  WordPressKit.podspec
Labels: releases

#812 Add upgradeURL to JetpackAssistantFeatureDetails
  Sources/WordPressKit/Models/Assistant/JetpackAssistantFeatureDetails.swift
Labels: [Type] Task
