Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2024-04, with the labels that each got.

#772 Improve Insight entities parsing
  Sources/WordPressKit/Models/Stats/Insights/StatsAllTimesInsight.swift
  Sources/WordPressKit/Models/Stats/Insights/StatsTagsAndCategoriesInsight.swift
Labels: enhancement

#783 Offline Mode: Add support for metadata
  Sources/WordPressKit/Models/RemotePostParameters.swift
Labels: [Type] Task

#786 Offline Mode: Fix encoding for some fields in the new XMLRPC endpoints
  Sources/WordPressKit/Models/RemotePostParameters.swift
Labels: bug

#785 Offline Mode: Add getPost(withID)
  Sources/WordPressKit/Services/PostServiceRemoteExtended.swift
  Sources/WordPressKit/Services/PostServiceRemoteREST+Extended.swift
  Sources/WordPressKit/Services/PostServiceRemoteXMLRPC+Extended.swift
  Sources/WordPressKit/Services/PostServiceRemoteXMLRPC.h
  Sources/WordPressKit/Services/PostServiceRemoteXMLRPC.m
Labels: bug

#792 Offline Mode: Switch to wp.editPost and wp.newPost
  CHANGELOG.md
  Sources/WordPressKit/Models/RemotePostParameters.swift
  Sources/WordPressKit/Services/PostServiceRemoteXMLRPC+Extended.swift
Labels: [Type] Task

#796 Fix an issue with parent page ID removal
  CHANGELOG.md
  Sources/WordPressKit/Models/RemotePostParameters.swift
Labels: bug

#797 Make StatsFollower Equatable
  CHANGELOG.md
  Sources/WordPressKit/Models/Stats/Insights/StatsDotComFollowersInsight.swift
Labels: [Type] Task
