Repository wordpress-mobile/WordPressKit-iOS, pull requests merged in 2024-11, with the labels that each got.

#819 [Tooling] SwiftLint: Use `linter` agent instead of `default` agent
  .buildkite/pipeline.yml
Labels: tooling

#822 Add support for sending magic links to inexistent accounts
  Sources/WordPressKit/Services/AccountServiceRemoteREST.h
  Sources/WordPressKit/Services/AccountServiceRemoteREST.m
Labels: enhancement

#823 Release 17.3.0
  CHANGELOG.md
  Gemfile.lock
  WordPressKit.podspec
Labels: releases
